---
kind: pipeline
type: docker
name: build

steps:
  - name: docker
    image: plugins/docker
    settings:
      registry: code.pztrn.name
      repo: code.pztrn.name/containers/npf-docker
      auto_tag: true
