---
kind: pipeline
type: docker
name: build

steps:
  - name: docker
    image: plugins/docker
    settings:
      docker:
        registry: code.pztrn.name
      username: drone
      password:
        from_secret: drone_secret
      repo: containers/npf-docker
      auto_tag: true
